/** @type {import('next').NextConfig} */
const {i18n} = require('./next-i18next.config');

const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  i18n,
  env: {
    REACT_APP_ISUNCLOUD_CONTACT_EMAIL: process.env.REACT_APP_ISUNCLOUD_CONTACT_EMAIL,
    REACT_APP_ISUNCLOUD_COPYRIGHT: process.env.REACT_APP_ISUNCLOUD_COPYRIGHT,
    REACT_APP_ISUN_NODE_NAME: process.env.REACT_APP_ISUN_NODE_NAME,
    /* Info: (20230707 - Julian) iSunCloud Taiwan */
    REACT_APP_ISUNCLOUD_TAIWAN_PHONE: process.env.REACT_APP_ISUNCLOUD_TAIWAN_PHONE,
    REACT_APP_ISUNCLOUD_TAIWAN_ADDRESS: process.env.REACT_APP_ISUNCLOUD_TAIWAN_ADDRESS,
    REACT_APP_ISUNCLOUD_TAIWAN_ADDRESS_IN_MAP:
      process.env.REACT_APP_ISUNCLOUD_TAIWAN_ADDRESS_IN_MAP,
    /* Info: (20230707 - Julian) iSunCloud Hong Kong */
    REACT_APP_ISUNCLOUD_HONGKONG_PHONE: process.env.REACT_APP_ISUNCLOUD_HONGKONG_PHONE,
    REACT_APP_ISUNCLOUD_HONGKONG_ADDRESS: process.env.REACT_APP_ISUNCLOUD_HONGKONG_ADDRESS,
    REACT_APP_ISUNCLOUD_HONGKONG_ADDRESS_IN_MAP:
      process.env.REACT_APP_ISUNCLOUD_HONGKONG_ADDRESS_IN_MAP,
    /* Info: (20230707 - Julian) iSunCloud USA */
    REACT_APP_ISUNCLOUD_USA_PHONE: process.env.REACT_APP_ISUNCLOUD_USA_PHONE,
    REACT_APP_ISUNCLOUD_USA_ADDRESS: process.env.REACT_APP_ISUNCLOUD_USA_ADDRESS,
  },
};

module.exports = nextConfig;
